name: 'Builder'
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: Build all in configs/
    runs-on: ubuntu:22.04
    steps:
      - name: Install build tools
        run: apt update && apt install libnewlib-arm-none-eabi binutils-arm-none-eabi gcc-arm-none-eabi
      - name: ls
        run: ls -latr && pwd

